### ISSUE TITLE
wip/ideas discussion

### ISSUE THREAD

**Issue by loosefish-scapegrace** [kyx0r/nextvi#115] opened 2024-09-03 23:59 UTC
been thinking about writing a manual page for nextvi. i think a manual page would be useful for organised documentation, an easy to understand list of keybinds and commands etc.

when/if i get around to writing it, will send a patch/pull request

**Comment by kyx0r** [comment] 2024-09-04 02:24
Great idea! The current readme is a bit a of a maze and somewhat expects the user to know what he is getting into. The only upside is that it is short.

**Comment by polluks** [comment] 2024-09-07 10:50
Well, the readme is like vi itself, rather compact.

**Comment by polluks** [comment] 2024-09-10 16:50
Like this? https://youtu.be/ZUdnHtvX4l4

**Comment by LaithOsama** [comment] 2024-09-10 21:34
I saw this before, a nice one but very basic.

**Comment by Un1q32** [comment] 2024-09-10 21:47
> What about a demo video?

Making one wouldn't be that hard, the problem would come whenever features get added or changed, the video would have to be remade which would be a lot harder then editing a man page.

**Comment by kyx0r** [comment] 2024-09-10 22:59
> What about a demo video? Every time I read the Readme, I see features I didn't even notice before and be amazed about how useful they could be. I'd love to see the lead programmer use all the features of this editor to the maximum, I can't imagine how productive this editor could be considering it's size and simpicity. I know it's a bit demanding and difficult, but I'm suggesting it out of curiosity.

Maybe in a few months. I've got ideas planned for new patches and some features to infinitely expand what is possible. Keep in mind that the project is not just about making something work, but it's also about making the said happen in the least number of lines of code physically possible and at highest raw cpu performance.

There are some things (code wise) I am still not happy with, part due to neatvi legacy. I do have to make a lot of conscious effort to not break any of the bidirectional stuff.

**Comment by LaithOsama** [comment] 2024-09-10 23:10
> Making one wouldn't be that hard, the problem would come whenever features get added or changed, the video would have to be remade which would be a lot harder then editing a man page.

Fair enough

> As of 2022-01-01 Nextvi development has been driven to completion.
- The Readme

But I didn't know the current status of this quote, so I didn't take that into account.
In general I don't think it will be a really big issue, as users can stay in touch with newer changes even after the demo.

**Comment by LaithOsama** [comment] 2024-09-10 23:15
> Maybe in a few months. I've got ideas planned for new patches and some features to infinitely expand what is possible. Keep in mind that the project is not just about making something work, but it's also about making the said happen in the least number of lines of code physically possible and at highest raw cpu performance.
> 
> There are some things (code wise) I am still not happy with, part due to neatvi legacy. I do have to make a lot of conscious effort to not break any of the bidirectional stuff.

Cool, good luck bro.
What I wanted was to figure out the most efficient way to employ and make the best use of the features, but it's not necessary and I hope you'll take your time.

**Comment by kyx0r** [comment] 2024-09-10 23:24
That quote  held true for some time I guess. I am just a lot more rigorous about what I put in master and what I put in patches. I think it would be fair to say that development is not over, but what you see in master is what I deemed as feature complete. 

For everyone in the room, here are my plans:
1. Refactor ren.c (it's too damn complicated to go from visial position -> character position -> character offset. Actually might be impossible if text reordered due to information loss.) Reduce lines of code.
2. With ren.c refactor relative line number should be able to determine the position *more* correctly.
4. Look into the half redraw and syn_blockhl scenario, it can now highlight stuff incorrectly if scrolled in a certain way.
5. If no other issues found proceed to implement the soft line wrap, I know how this can be done without a million changes everywhere.

**Comment by kyx0r** [comment] 2024-09-10 23:40
5. Ability to inject / manipulate syntax highlight in other ways (more direct and complete) besides the regex. (optional patch)
6. Ability to redirect text printed by ex_cprint into a register (probably on master if small enough)

**Comment by kyx0r** [comment] 2024-09-10 23:43
7.  Explore some interesting ways to extend the ex macros into something closer resembling a programming language with control flow, etc. (optional patch)

**Comment by LaithOsama** [comment] 2024-09-12 10:31
Wow! Keep cooking mate, this project has unreal potential.
This roadmap is impressive but it's not easy at all, you're closer to making a complete rewrite of `neatvi`.
Unfortunately for me, I don't know C, I would have loved to help even in the simplest of ways.

**Comment by kyx0r** [comment] 2024-09-15 02:15
> Wow! Keep cooking mate, this project has unreal potential. This roadmap is impressive but it's not easy at all, you're closer to making a complete rewrite of `neatvi`. Unfortunately for me, I don't know C, I would have loved to help even in the simplest of ways.

Thank you! Don't worry, what I would appreciate is feedback on some Arabic settings. It's hard for me to judge as I don't know the language too well. But after some time testing I think the changes in the latest commit right now look or, at least the text rendering, insertion operations, ordering and :se hlr option looked right.

**Comment by LaithOsama** [comment] 2024-09-15 09:16
I'll do my best to assist with this. I'm glad to see that you're following the original project's vision, ensuring everyone can use the editor and not being restricted to one writing direction (as many editors are limited to LTR). For a text editor, implementing bidirectional text compatibility in a sensible way is a crucial feature, it makes it a favorable option for many users and it's one of the standout aspects of this project that sets it apart from others.

However, I can understand that Arabic can be very complex in the terminals, particularly when handling [Arabic diacritics](https://en.wikipedia.org/wiki/Arabic_diacritics) (see [neatvi/#54](https://github.com/aligrudi/neatvi/issues/54)).

**Comment by LaithOsama** [comment] 2024-09-15 09:23
> I think the changes in the latest commit right now look or, at least the text rendering, insertion operations, ordering and :se hlr option looked right.

I can confirm that in the moment, you're doing great work.
Also I apologize for going off topic. Sorry for the OP.

**Comment by Un1q32** [comment] 2024-09-16 22:12
> I don't know C, I would have loved to help even in the simplest of ways.

Hacking on nextvi was a huge help when I was first learning.  I made a few patches that added features from POSIX (c_option.patch, readonly.patch, exrc.patch).  Someday I intend to do a rewrite to make nextvi fully POSIX compliant, but that would probably be way too big to be a patch.

**Comment by kyx0r** [comment] 2024-09-16 22:48
> Hacking on nextvi was a huge help when I was first learning. I made a few patches that added features from POSIX (c_option.patch, readonly.patch, exrc.patch). Someday I intend to do a rewrite to make nextvi fully POSIX compliant, but that would probably be way too big to be a patch.

I think it would be cool to have something like a posix strict mode as a patch or a separate branch. Would you remove all the existing non posix features though? I suppose that's what the strict mode would be for. But some things are not so easy to discern, like syntax highlight is not in posix, would you remove it even though it doesn't change any posix functionality? Or would you just set the value of xhl to 0 and call it a day?

Anyways, I'd be happy to answer any questions you may have if you decide to do this. At this point I can probably rewrite entire nextvi from memory. No joke, I literally have every line of code in it memorized.

**Comment by Un1q32** [comment] 2024-09-16 23:07
No I wouldn't remove non-POSIX features, just add all POSIX features not implemented.  Part of this would be changing how some systems work as they are fundamentally incompatible with POSIX, like edit options, which are supposed to be per-buffer.  In readonly.patch I had to emulate the behavior of `:set readonly` only affecting the current buffer by making an ex command `:ro` that toggled readonly mode for the current buffer.  An easy way to see this is by opening 2 files in vim and nextvi and setting tabstop/tbs in one of them, then switching buffers, in nextvi the change affects all open buffers while in vim it only affects the buffer the `:set` command was run in.

I think this explanation is mostly correct but it's been a while since I've read the POSIX spec over or checked the behavior of different implementations.  It's possible some of this is just stuff vim or someone else did that everyone else copied, but isn't actually mandated by the spec.

**Comment by kyx0r** [comment] 2024-09-16 23:58
I see. Btw, you can do a per buffer flag the same way td (text direction) is set. Pretty sure if you :se td=-2 and open another buffer it will still default to td=1 on the new buffer and remember the setting it has. So this system is technically already implemented, you just have to make further use of it.

**Comment by loosefish-scapegrace** [comment] 2024-09-17 01:52
i've started working on this. not much done so far, but current progress is attached. (you can view it with `man -l vi.1.txt`)

maybe a draft pull request or a temporary branch or something for this is a good idea so other people can help write this (especially since i'm not too familiar with nextvi's internals and i'm not great at code comprehension)

[vi.1.txt](https://github.com/user-attachments/files/17021896/vi.1.txt)

**Comment by loosefish-scapegrace** [comment] 2024-09-17 01:57
> 7. Explore some interesting ways to extend the ex macros into something closer resembling a programming language with control flow, etc. (optional patch)

i like the idea of making nextvi extensible like this, but i think building on `ex` for this isn't a great solution. i feel like it would end up just turning into vimscript.

i have a few maybe-viable ideas for easier extensibility, maybe something like Dillo's plugin system where an executable communicates with nextvi via an internal protocol, or something like MPV's C scripts where .so binaries in a certain directory are able to extend functionality, maybe even exposing a 9p interface and then just being able to use a shell script?

**Comment by kyx0r** [comment] 2024-09-17 02:18
> i've started working on this. not much done so far, but current progress is attached. (you can view it with `man -l vi.1.txt`)
> 
> maybe a draft pull request or a temporary branch or something for this is a good idea so other people can help write this (especially since i'm not too familiar with nextvi's internals and i'm not great at code comprehension)
> 
> [vi.1.txt](https://github.com/user-attachments/files/17021896/vi.1.txt)

Great start, I'll have a look. Putting on a branch sounds reasonable to me.

> > 7. Explore some interesting ways to extend the ex macros into something closer resembling a programming language with control flow, etc. (optional patch)
> 
> i like the idea of making nextvi extensible like this, but i think building on `ex` for this isn't a great solution. i feel like it would end up just turning into vimscript.

I completely understand. This won't turn into a vimscript. I'm thinking something like --filter_complex in ffmpeg. Currently ex scripts already resemble what I was aiming for, but it's missing things like if statements. Extremely dense and cryptic macros. It shall not grow out of that, and I would have no desire to maintain a full programming language. C alone is enough :)

> 
> i have a few maybe-viable ideas for easier extensibility, maybe something like Dillo's plugin system where an executable communicates with nextvi via an internal protocol, or something like MPV's C scripts where .so binaries in a certain directory are able to extend functionality, maybe even exposing a 9p interface and then just being able to use a shell script?

Totally, nextvi can be built like a library. Actually that is what vi.h is for ;)
We'll see, this is kinda far out. I like to take things one small step at a time, to properly cook the best quality solutions.

**Comment by kyx0r** [comment] 2024-09-17 03:26
I've created a branch called manual.
https://github.com/kyx0r/nextvi/tree/manual

You guys can submit PRs to it. The idea is that this will eventually replace the good ol hand
formatted README we have right now. For obvious reasons the README will stay in plain ascii
as I want the users to be able to read it using vi itself. The roff version will stay on the branch though.
I think this is a fair way to organize this. Later on if I ever have enough courage to make a version 1.0
release (first ever in 4 years! lol) we can ship the man page with it all together.

**Comment by dostoievsky** [comment] 2024-09-27 15:46
> I've created a branch called manual. https://github.com/kyx0r/nextvi/tree/manual

You mean to rewrite every command in the manual? 
Riping the data of other manuals such as vi(1) is not an option?

**Comment by kyx0r** [comment] 2024-09-27 16:35
> > I've created a branch called manual. https://github.com/kyx0r/nextvi/tree/manual
> 
> You mean to rewrite every command in the manual? Riping the data of other manuals such as vi(1) is not an option?

I think we have an opportunity to do way better than any other vi(1) manual. Plus I know how everything works which means it will be accurately documented.

**Comment by Un1q32** [comment] 2024-10-21 21:08
> Explore some interesting ways to extend the ex macros into something closer resembling a programming language with control flow, etc. (optional patch)

Why not just make an ex command that runs some shell command and runs the stdout from it as an ex command.  In my neovim config the only times I really do complex stuff like that is for different OS checks and using environment variables.  I could do pretty much everything I need to with a shell script, or something in C if I needed to do something complex fast.  You could pass info about the session to the program with environment vars.

```sh
#!/bin/sh

# Set the length of tabs based on the language

case "$NEXTVI_FILETYPE" in
    python)
        # 2 spaces for python scripts
        echo 'se tbs=2;'
    ;;

    c|sh)
        # 4 spaces for C and shell scripts
        echo 'se tbs=4;'
    ;;

    *)
        # 8 spaces for everything else
        echo 'se tbs=8;'
    ;;
esac
```

If people like this idea I could whip up a patch for it when I get home.

**Comment by kyx0r** [comment] 2024-10-22 05:03
> > Explore some interesting ways to extend the ex macros into something closer resembling a programming language with control flow, etc. (optional patch)
> 
> Why not just make an ex command that runs some shell command and runs the stdout from it as an ex command. In my neovim config the only times I really do complex stuff like that is for different OS checks and using environment variables. I could do pretty much everything I need to with a shell script, or something in C if I needed to do something complex fast. You could pass info about the session to the program with environment vars.

Yeah, I think kaukoune does something like this a lot. I'd love to try a demo xD

In other news, manual page is done. It only took 10 hours! Well, I made sure not to miss
anything, but there is still a chance I did. Proof reading or any other suggestions on fomating
would help too.

**Comment by kyx0r** [comment] 2024-11-04 14:16
I'm actually looking at modal, to potentially give ex ALU capabilities. Modal implementation is 300 lines of C and could play nice with ex.
https://wiki.xxiivv.com/site/modal.html

**Comment by polluks** [comment] 2024-11-04 21:26
What do you do in ex-Modal for example?

**Comment by kyx0r** [comment] 2024-11-04 21:40
> What do you do in ex-Modal for example?

Potentially implementing a turing complete logic in ex. For example we can do a simple string search like :/int/
but we have no syntax and no way of asserting the result of that search. Then if you try to make an ex script that
relies on the search you can't add any logic to see if this search failed or not.

**Comment by kyx0r** [comment] 2024-11-04 21:43
So if you add vi/ex hooks into the modal meta language you can potentially create something really cool and infinitely useful. And the best part is that the syntax is compatible and compact enough to keep everything else as is.

**Comment by loosefish-scapegrace** [comment] 2024-11-04 22:04
having something like Modal as an external scripting language could be cool.
Maybe some dialect of Forth could be nice for this too, when it comes to smallness? Although hooking ex into the forth parser would maybe be a bit wonky

Even more out there a suggestion, extensibility through a 9p interface? then you don't even need to include an embedded language at all

**Comment by kyx0r** [comment] 2024-11-06 15:30
9p Interface too complicated it seems. And well, not self contained

**Comment by unrealapex** [comment] 2024-11-09 01:57
Ideas I would like to propose are adding `cursorline` from Vim to make the current line easy to find and adding more text objects. The additional text objects Vim adds are very convenient(see `:help motion`).

**Comment by kyx0r** [comment] 2024-11-09 02:14
> Ideas I would like to propose are adding `cursorline` from Vim to make the current line easy to find and adding more text objects. The additional text objects Vim adds are very convenient(see `:help motion`).

Hello! Nextvi already has cursorline like option. Try ```:se hll```. Now as mentioned in the manual, this option only works on defined filetypes in conf.c. For example .diff filetype doesn't have it, so it will not work on that. You can add it if you like!

Regarding motions, a lot of them can be created by making your own custom macros, which is why I don't add much new core keybinds.

(Update for people in the thread)
Here is the new shell scripting patch:
https://github.com/kyx0r/nextvi/blob/patches/ex-scripting.patch

With this you can execute conditionals, leveraging the shell.

**Comment by unrealapex** [comment] 2024-11-09 02:52
Thanks for the speedy response! I've only been hacking on Nextvi for a day, but I can give it a try.

**Comment by unrealapex** [comment] 2024-11-09 03:24
Enabling GitHub discussions for this repository might remedy what this issue is for. People could propose ideas there and if they gain enough discussion/traction they can be submitted as feature requests here in the issues.

**Comment by unrealapex** [comment] 2024-11-09 07:53
Having a shell script that fetches upstream commits would be convenient to keep your own fork updated. I propose having a fetch script like this as a patch or mentioned in the README:
```sh
#!/bin/sh

git switch -c upstream
git pull https://github.com/kyx0r/nextvi
git switch master
git rebase --rebase-merges upstream
git branch -D upstream
```

**Comment by kyx0r** [comment] 2024-11-09 14:09
> Having a shell script that fetches upstream commits would be convenient to keep your own fork updated. I propose having a fetch script like this as a patch or mentioned in the README:
> 
> ```
> #!/bin/sh
> 
> git switch -c upstream
> git pull https://github.com/kyx0r/nextvi
> git switch master
> git rebase --rebase-merges upstream
> git branch -D upstream
> ```

I like that, actually quite convenient because it can straight up go into the cbuild.sh script.
./cbuild.sh fetch
For ideological reasons, I prefer to not add any new files to master branch to keep the
mental model the same.

**Comment by kyx0r** [comment] 2024-11-09 14:59
> Enabling GitHub discussions for this repository might remedy what this issue is for. People could propose ideas there and if they gain enough discussion/traction they can be submitted as feature requests here in the issues.

Ok, I've created it here:
https://github.com/kyx0r/nextvi/discussions/137

Closing this thread.

**Closed by kyx0r** 2024-11-09 14:59 UTC

**Comment by unrealapex** [comment] 2024-11-09 23:24
> Regarding motions, a lot of them can be created by making your own custom macros, which is why I don't add much new core keybinds.

This would be a great patch idea!
